// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8PHD5hgETrv24ALaHcCvRyLGXGDe4qO0',
    appId: '1:1057706468782:web:dd5e6cea6a56b404e5143f',
    messagingSenderId: '1057706468782',
    projectId: 'food-app-b1ad8',
    authDomain: 'food-app-b1ad8.firebaseapp.com',
    storageBucket: 'food-app-b1ad8.appspot.com',
    measurementId: 'G-9WLZQC68WE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZraGeq8RKSSbyHHc5dSVfCxDtDSrOhyI',
    appId: '1:1057706468782:android:13ae5fbf473f8424e5143f',
    messagingSenderId: '1057706468782',
    projectId: 'food-app-b1ad8',
    storageBucket: 'food-app-b1ad8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0DqxgDtr0ULCz7HwzN0Mc8QixE2k3f4E',
    appId: '1:1057706468782:ios:56c0e787459f556fe5143f',
    messagingSenderId: '1057706468782',
    projectId: 'food-app-b1ad8',
    storageBucket: 'food-app-b1ad8.appspot.com',
    iosClientId: '1057706468782-flbr9nkcqmkphvr6c5kvhhub85chkddr.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfoodApp',
  );
}
